version: "3.3"


services:

#  database:
#    image: library/postgres:12
#    container_name: crm-bd
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=crm
#    ports:
#      - 5432:5432
#    volumes:
#      - ${WORK_DATA}/database:/var/lib/postgresql/data
#      - ./initdb:/docker-entrypoint-initdb.d

#  auth-server:
#    image: jboss/keycloak
#    container_name: crm-auth-server
#    environment:
#      - DB_VENDOR=postgres
#      - DB_DATABASE=crm
#      - DB_ADDR=crm
#      - DB_SCHEMA=keycloak
#      - DB_USER=keycloak
#      - DB_PASSWORD=keycloak
#      - KEYCLOAK_LOGLEVEL=DEBUG
#      - PROXY_ADDRESS_FORWARDING=true
#      - KEYCLOAK_USER=${KEYCLOAK_USER}
#      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
#      - DEBUG_PORT=*:8787
#    ports:
#      - 8087:8080
#      - 8787:8787
#    depends_on:
#      - crm-bd
#    links:
#      - "crm-bd:crm-bd"

  postgres:
    container_name: postgres
    image: library/postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - ${WORK_DATA}/database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: crm
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
#    links:
#      - "postgres:postgres"